config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "tops/main"
  post "tops/login"
  root "tops#main"
  get "tops/logout"
  get "tops/new"
  post "tops/signup"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
    def main
        if session[:login_uid] != nil
            render 'main'
        else
            render "login"
        end
    end

    def login
        user = User.find_by(uid: params[:uid])
        if user && BCrypt::Password.new(user.pass) == params[:pass]
            session[:login_uid] = params[:uid]
            redirect_to tops_main_path
        else
            render "error"
        end
    end
    
    def logout
        session.delete(:login_uid)
        redirect_to tops_main_path
    end
    
    def new
        render "signup"
    end
    
    def signup
        signup_pass = BCrypt::Password.create(params[:pass])
        user = User.new(uid: params[:uid], pass: signup_pass)
        user.save
        session[:login_uid] = params[:uid]
        redirect_to tops_main_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CS2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tops/error.html.erb
エラーです!

<%= link_to "戻る", :back%>

app/views/tops/login.html.erb
<%= form_tag "/tops/login", method: :post, data: { turbo: false } do %>
    <%= label_tag :uid, "ユーザーID" %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, "パスワード" %>
    <%= password_field_tag :pass %>
    <%= submit_tag "登録" %>
<% end %>

app/views/tops/main.html.erb
<h1>ログイン中</h1>

<%= link_to "ログアウト", tops_logout_path %>

app/views/tops/signup.html.erb
<h1>登録画面</h1>
<%= form_tag "/tops/signup", method: :post, data: { turbo: false } do %>
    <%= label_tag :uid, "ユーザーID" %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, "パスワード" %>
    <%= password_field_tag :pass %>
    <%= submit_tag "登録" %>
<% end %>